spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/starwars
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    br.com.projeto.mundo_star_wars: INFO
    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [DOCKER] %-5level %logger{36} - %msg%n'

# Configurações JWT para Docker
jwt:
  secret: ${JWT_SECRET:minha-chave-secreta-super-segura-para-desenvolvimento-starwars-2024}
  expiration: ${JWT_EXPIRATION:86400000}